#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f}
Dir["./lib/*.rb"].each { |f| require f}

if ARGV.empty?
  loop do
    choose do |menu|
      menu.prompt = ""

      books_controller = BooksController.new
      genres_controller = GenresController.new

      menu.choice('Add a book') do
        loop do
          user_input = ask("What book would you like to add?")
          response = books_controller.add(user_input)
            say(response) unless response.nil?
            if /has\sbeen\sadded.$/.match(response)
          end
          user_input = ask("What is the book's primary genre?")
          response = genres_controller.add(user_input)
          say(response) unless response.nil?
          if /has\sbeen\sadded.$/.match(response)
            break
          end
        end
      end
      menu.choice('Edit book info') do
        user_input = ask("What book would you like to edit?")
        response = books_controller.edit(user_input)
      end
      menu.choice('View the book list') do
        books_controller.index
      end
      menu.choice('Exit the program') do
        say("Go read something!\n")
        exit
      end
    end
  end
else
  puts "[Help] Run as: ./whatcha_reading"
end


