production:
  adapter: sqlite3
  database: db/whatcha_reading_production.sqlite
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/whatcha_reading_test.sqlite
  pool: 5
  timeout: 5000